atarashii_api_homepage:
    path:  /
    defaults: { _controller: AtarashiiAPIBundle:Default:index }

atarashii_api_animelist:
    path:  /animelist/{username}
    defaults: { _controller: AtarashiiAPIBundle:AnimeList:get, _format: json }
    requirements:
        _method: GET

atarashii_api_animelist:
    path:  /animelist/anime
    defaults: { _controller: AtarashiiAPIBundle:AnimeList:post, _format: json }
    requirements:
        _method: POST

atarashii_api_mangalist:
    path:  /mangalist/{username}
    defaults: { _controller: AtarashiiAPIBundle:MangaList:get, _format: json }
    requirements:
        _method: GET

atarashii_api_userprofile:
    path:  /profile/{username}
    defaults: { _controller: AtarashiiAPIBundle:User:getProfile, _format: json }
    requirements:
        _method: GET

atarashii_api_userprofile_friends:
    path:  /friends/{username}
    defaults: { _controller: AtarashiiAPIBundle:User:getFriends, _format: json }
    requirements:
        _method: GET

atarashii_api_popular_anime:
    path:  /anime/popular
    defaults: { _controller: AtarashiiAPIBundle:Top:getPopularAnime, _format: json }
    requirements:
        _method: GET

atarashii_api_popular_manga:
    path:  /manga/popular
    defaults: { _controller: AtarashiiAPIBundle:Top:getPopularManga, _format: json }
    requirements:
        _method: GET

atarashii_api_top_anime:
    path:  /anime/top
    defaults: { _controller: AtarashiiAPIBundle:Top:getTopAnime, _format: json }
    requirements:
        _method: GET

atarashii_api_top_manga:
    path:  /manga/top
    defaults: { _controller: AtarashiiAPIBundle:Top:getTopManga, _format: json }
    requirements:
        _method: GET

atarashii_api_just_anime:
    path:  /anime/just_added
    defaults: { _controller: AtarashiiAPIBundle:Upcoming:getAnimeJustadded, _format: json }
    requirements:
        _method: GET

atarashii_api_just_manga:
    path:  /manga/just_added
    defaults: { _controller: AtarashiiAPIBundle:Upcoming:getMangaJustadded, _format: json }
    requirements:
        _method: GET

atarashii_api_upcoming_anime:
    path:  /anime/upcoming
    defaults: { _controller: AtarashiiAPIBundle:Upcoming:getAnimeUpcoming, _format: json }
    requirements:
        _method: GET

atarashii_api_upcoming_manga:
    path:  /manga/upcoming
    defaults: { _controller: AtarashiiAPIBundle:Upcoming:getMangaUpcoming, _format: json }
    requirements:
        _method: GET

atarashii_api_search_anime:
    path:  /anime/search
    defaults: { _controller: AtarashiiAPIBundle:Search:getAnime, _format: json }
    requirements:
        _method: GET

atarashii_api_search_manga:
    path:  /manga/search
    defaults: { _controller: AtarashiiAPIBundle:Search:getManga, _format: json }
    requirements:
        _method: GET

atarashii_api_verify_credentials:
    path:  /account/verify_credentials
    defaults: { _controller: AtarashiiAPIBundle:Verify:Verify, _format: json }
    requirements:
        _method: GET