atarashii_api_homepage:
    path:  /
    defaults: { _controller: AtarashiiAPIBundle:Default:index }

atarashii_api_animelist:
    path:  /animelist/{username}
    defaults: { _controller: AtarashiiAPIBundle:AnimeList:get, _format: json }
    requirements:
        _method: GET

atarashii_api_mangalist:
    path:  /mangalist/{username}
    defaults: { _controller: AtarashiiAPIBundle:MangaList:get, _format: json }
    requirements:
        _method: GET

atarashii_api_userprofile:
    path:  /profile/{username}
    defaults: { _controller: AtarashiiAPIBundle:User:getProfile, _format: json }
    requirements:
        _method: GET

atarashii_api_userprofile_friends:
    path:  /friends/{username}
    defaults: { _controller: AtarashiiAPIBundle:User:getFriends, _format: json }
    requirements:
        _method: GET

atarashii_api_popular_anime:
    path:  /anime/popular
    defaults: { _controller: AtarashiiAPIBundle:Popular:getAnime, _format: json }
    requirements:
        _method: GET

atarashii_api_popular_manga:
    path:  /manga/popular
    defaults: { _controller: AtarashiiAPIBundle:Popular:getManga, _format: json }
    requirements:
        _method: GET

atarashii_api_top_anime:
    path:  /anime/top
    defaults: { _controller: AtarashiiAPIBundle:Top:getAnime, _format: json }
    requirements:
        _method: GET

atarashii_api_top_manga:
    path:  /manga/top
    defaults: { _controller: AtarashiiAPIBundle:Top:getManga, _format: json }
    requirements:
        _method: GET

atarashii_api_search_anime:
    path:  /anime/search
    defaults: { _controller: AtarashiiAPIBundle:Search:getAnime, _format: json }
    requirements:
        _method: GET

atarashii_api_search_manga:
    path:  /manga/search
    defaults: { _controller: AtarashiiAPIBundle:Search:getManga, _format: json }
    requirements:
        _method: GET